version: "3.7"
services:
  api:
    container_name: 'api'
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    links:
      - mongo
    volumes:
      - .:/api
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - '27017:27017'
    command: [ --auth ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./db/mongo:/data/db